### ISSUE TITLE
Search result searching by name is not always showing up

### ISSUE THREAD

**Issue by miyabitanimchi** [BlackStone8960/Musician-First#25]
Search result doesn't show up basically when there is a white space(s).
If the user you want to find by searching by name is "Taichi Ishiguro",
if you input:

- "Taichi" => ok
- "taichi" => ok
- "taiChi" => ok
- "Taichi " => no
- " Taichi" => no
- "Taichi Ishi" => no
- "Taichi Ishiguro" => no

**Comment by YumiKimbara** [comment]
Fixed
