### ISSUE TITLE
User(s) searched by name show up anywhere in a genre when there is no user matched with the genre

### ISSUE THREAD

**Issue by miyabitanimchi** [BlackStone8960/Musician-First#26]
For a user shown up by searching by name, without refreshing the user will show up in any genre which doesn't have any users matched with the genre. For the genre which has users matched already, it will show the result matched by the genre <br/>
![seaching_by_name_bug](https://user-images.githubusercontent.com/69213541/135224450-da233962-225c-4976-a987-69aaba05b746.gif)
.

**Comment by YumiKimbara** [comment]
Fixed
