### ISSUE TITLE
Can't delete user account after time passes from last time user logged in

### ISSUE THREAD

**Issue by BlackStone8960** [BlackStone8960/Musician-First#5]
After time passed from last time user logged in, the error message below will be appeared and user can't delete his/her account.
![image](https://user-images.githubusercontent.com/60183777/127574534-340efa6c-8c97-409f-b43d-606b3d236e62.png)

**Comment by Kit486759** [comment]
- Reason of issue: It is a security action in firebase auth to block some sensitive actions as deleting a user.
- Solution: Added re-auth function and have re-auth credential check before deleting user.
