### ISSUE TITLE
Can't go back to musician's info as the previous page when Back button on the legal docs was clicked

### ISSUE THREAD

**Issue by miyabitanimchi** [BlackStone8960/Musician-First#7]
The Back button on each legal document always redirects to the previous page the user was on. When the previous page is musician's info, the error below occurs.

<img width="943" alt="スクリーンショット 2021-08-11 午前0 52 40" src="https://user-images.githubusercontent.com/69213541/128992788-8d16bc3b-cc02-47ad-b1af-9e1501a8a7bc.png">

**Comment by Kit486759** [comment]
- **Reason of issue**:  The % symbol has a conflict with the space( space will convert to %20 after decode).
- **Solution**: Added replace() method to assign % symbol as %25 before decode.
