### ISSUE TITLE
The phone number isn't appeared if user input country code into profile

### ISSUE THREAD

**Issue by BlackStone8960** [BlackStone8960/Musician-First#73]
For example, if user input phone number like +1 1234567890, it won't be appeared at profile page and warning message will appear as below.

<img width="272" alt="Screen Shot 2021-11-12 at 6 25 49 PM" src="https://user-images.githubusercontent.com/60183777/141602552-21b71a0a-1b0a-4ca4-bc73-3f22a394f60b.png">

**Comment by YumiKimbara** [comment]
fixed it
