### ISSUE TITLE
When closing chat window, the error occurs

### ISSUE THREAD

**Issue by BlackStone8960** [BlackStone8960/Musician-First#79]
When closing chat window in other users' page, the error like following picture appears on console (but there are no effects to usability for now)
<img width="463" alt="Screen Shot 2021-11-13 at 7 28 57 PM" src="https://user-images.githubusercontent.com/60183777/141666287-ef39b01f-1178-473a-b147-6e68f49d92a8.png">

**Comment by Kit486759** [comment]
Reason of error:
When turning on the chatbox, then scroll event listener was added. When closing the chatbox, that listener is still there but the element in DOM is already unmounted that's why return error property is null.
Fix:
Added function to close that event listener when closing the chatbox.
